
--создание таблиц в соответствии с ТЗ

CREATE TYPE VITAL AS ENUM ('Yes', 'No');

CREATE TABLE Product
(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL UNIQUE,
	Vital VITAL NOT NULL,
	Type VARCHAR(100) NOT NULL,
	Prescription VARCHAR(100)
);

CREATE TABLE Pharmacy
(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	City VARCHAR(50) NOT NULL,
	Format VARCHAR(50) NOT NULL
);

CREATE TABLE Sale
(
	Id SERIAL PRIMARY KEY,
	SaleTime DATE NOT NULL,
	PharmacyId INTEGER REFERENCES Pharmacy (Id) ON DELETE CASCADE NOT NULL,
	ProductId INTEGER REFERENCES Product (Id) ON DELETE CASCADE NOT NULL,
	PacksNumber INTEGER NOT NULL,
	Price NUMERIC NOT NULL
);